# Generated by Django 5.1.2 on 2024-10-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('images', models.ImageField(upload_to='photos/blog')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
